In [1]:
from tensorflow.keras.preprocessing.text import one_hot

2025-12-29 21:47:11.559025: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-12-29 21:47:11.597407: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-12-29 21:47:12.812347: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.


In [2]:
#sentences
sent= [
    'I love my dog',
    'I love my cat',
    'You love my dog!',
    'Do you think my dog is amazing?'
]

In [3]:
sent

['I love my dog',
 'I love my cat',
 'You love my dog!',
 'Do you think my dog is amazing?']

In [4]:
# define the vocuabulary size
voc_size=10000

In [5]:
#  one hot representation
one_hot_representations = [one_hot(words, voc_size) for words in sent]
one_hot_representations

[[2423, 1087, 5906, 1695],
 [2423, 1087, 5906, 5460],
 [3685, 1087, 5906, 1695],
 [520, 3685, 6205, 5906, 1695, 591, 9804]]

In [12]:
# word embedding representation 
from tensorflow.keras.layers import Embedding , Input
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential


In [7]:
import numpy as np

In [16]:
# pad the sequences to have same length
sent_length=8
embedded_docs=pad_sequences(one_hot_representations,maxlen=sent_length,padding='pre')
print(embedded_docs)


[[   0    0    0    0 2423 1087 5906 1695]
 [   0    0    0    0 2423 1087 5906 5460]
 [   0    0    0    0 3685 1087 5906 1695]
 [   0  520 3685 6205 5906 1695  591 9804]]


In [9]:
#  feature representation 
dim = 10


In [13]:
model = Sequential()
model.add(Input(shape=(sent_length,)))
model.add(Embedding(voc_size,dim,))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step


2025-12-29 21:50:49.292956: I external/local_xla/xla/service/service.cc:163] XLA service 0x7a6380002a20 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2025-12-29 21:50:49.292976: I external/local_xla/xla/service/service.cc:171]   StreamExecutor device (0): NVIDIA GeForce RTX 3050 Laptop GPU, Compute Capability 8.6
2025-12-29 21:50:49.311948: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:473] Loaded cuDNN version 91701
I0000 00:00:1767025249.349882  323232 device_compiler.h:196] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


array([[[-0.01023825, -0.01541942,  0.02190597, -0.02620977,
         -0.03211169,  0.02096686, -0.03449392,  0.03112708,
          0.04330591, -0.03158297],
        [-0.01023825, -0.01541942,  0.02190597, -0.02620977,
         -0.03211169,  0.02096686, -0.03449392,  0.03112708,
          0.04330591, -0.03158297],
        [-0.01023825, -0.01541942,  0.02190597, -0.02620977,
         -0.03211169,  0.02096686, -0.03449392,  0.03112708,
          0.04330591, -0.03158297],
        [-0.01023825, -0.01541942,  0.02190597, -0.02620977,
         -0.03211169,  0.02096686, -0.03449392,  0.03112708,
          0.04330591, -0.03158297],
        [ 0.02552832,  0.01166537,  0.02280003, -0.01000197,
         -0.00846564,  0.02830683,  0.04521406,  0.04730535,
          0.02292608, -0.04775497],
        [-0.04397235, -0.04769924,  0.00257125,  0.01313776,
          0.02639883, -0.04341394,  0.01800944, -0.02143649,
         -0.01274751, -0.04333984],
        [ 0.0155995 , -0.02379956,  0.03567356,  0.0

In [ ]:
embedded_docs[0]
model.predict(embedded_docs[::])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step


array([[[-0.01023825, -0.01541942,  0.02190597, -0.02620977,
         -0.03211169,  0.02096686, -0.03449392,  0.03112708,
          0.04330591, -0.03158297],
        [-0.01023825, -0.01541942,  0.02190597, -0.02620977,
         -0.03211169,  0.02096686, -0.03449392,  0.03112708,
          0.04330591, -0.03158297],
        [-0.01023825, -0.01541942,  0.02190597, -0.02620977,
         -0.03211169,  0.02096686, -0.03449392,  0.03112708,
          0.04330591, -0.03158297],
        [-0.01023825, -0.01541942,  0.02190597, -0.02620977,
         -0.03211169,  0.02096686, -0.03449392,  0.03112708,
          0.04330591, -0.03158297],
        [ 0.02552832,  0.01166537,  0.02280003, -0.01000197,
         -0.00846564,  0.02830683,  0.04521406,  0.04730535,
          0.02292608, -0.04775497],
        [-0.04397235, -0.04769924,  0.00257125,  0.01313776,
          0.02639883, -0.04341394,  0.01800944, -0.02143649,
         -0.01274751, -0.04333984],
        [ 0.0155995 , -0.02379956,  0.03567356,  0.0

: 